const profissoes = [
  "Acupunturista",
  "Açougueiro(a)",
  "Administrador(a)",
  "Advogado(a)",
  "Advogado(a) trabalhista",
  "Agente de seguros",
  "Agente de viagens",
  "Agricultor(a)",
  "Alfaiate/Alfaitaria",
  "Alinhador(a) de pneus",
  "Almoxarife",
  "Animador(a) de festas",
  "Antiquário(a)",
  "Antropólogo(a)",
  "Apicultor(a)",
  "Arqueólogo(a)",
  "Arquiteto(a)",
  "Arquiteto(a) de software",
  "Artista de circo",
  "Artista plástico(a)",
  "Ascensorista",
  "Assessor(a) de imprensa",
  "Assistente administrativo(a)",
  "Assistente social",
  "Astrônomo(a)",
  "Atendente de telemarketing",
  "Atleta",
  "Ator/Atriz",
  "Auditor(a)",
  "Auditor(a) fiscal",
  "Autônomo(a)",
  "Auxiliar de cozinha",
  "Babá",
  "Bailarino(a)",
  "Balconista",
  "Barbeiro(a)",
  "Barista",
  "Bibliotecário(a)",
  "Bicicleteiro(a)",
  "Biólogo(a)",
  "Biomédico(a)",
  "Bioquímico(a)",
  "Biotecnólogo(a)",
  "Bombeiro(a)",
  "Borracheiro(a)",
  "Cabeleireiro(a)",
  "Caixa de supermercado",
  "Camareiro(a)",
  "Caminhoneiro(a)",
  "Carpinteiro(a)",
  "Carteiro(a)",
  "Caseiro(a)",
  "Cenógrafo(a)",
  "Ceramista",
  "Cerimonialista",
  "Chapeiro(a)",
  "Chaveiro(a)",
  "Chef de cozinha",
  "Churrasqueiro(a)",
  "Cientista",
  "Cientista de dados",
  "Cientista político(a)",
  "Cineasta",
  "Coach",
  "Cobrador(a) de ônibus",
  "Comediante",
  "Comissário(a) de bordo",
  "Compositor(a)",
  "Confeiteiro(a)",
  "Consultor(a) de beleza",
  "Consultor(a) de RH",
  "Consultor(a) financeiro(a)",
  "Controlador(a) de qualidade",
  "Controlador(a) de tráfego aéreo",
  "Corretor(a) de imóveis",
  "Corretor(a) de seguros",
  "Costureiro(a)",
  "Cozinheiro(a)",
  "Cuidador(a) de idosos",
  "Dançarino(a)",
  "Decorador(a)",
  "Defensor(a) público(a)",
  "Dentista",
  "Despachante",
  "Designer de moda",
  "Designer gráfico(a)",
  "Designer de interiores",
  "Desenvolvedor(a) de software",
  "Digitador(a)",
  "Diarista",
  "DJ",
  "Doceria",
  "Economista",
  "Ecólogo(a)",
  "Editor(a) de vídeo",
  "Educador(a) físico(a)",
  "Eletricista",
  "Eletrônico(a)",
  "Embalador(a)",
  "Encanador(a)",
  "Enfermeiro(a)",
  "Engenheiro(a)",
  "Engenheiro(a) agrícola",
  "Engenheiro(a) agrônomo(a)",
  "Engenheiro(a) ambiental",
  "Engenheiro(a) biomédico(a)",
  "Engenheiro(a) civil",
  "Engenheiro(a) de alimentos",
  "Engenheiro(a) de computação",
  "Engenheiro(a) de materiais",
  "Engenheiro(a) de minas",
  "Engenheiro(a) de petróleo",
  "Engenheiro(a) de produção",
  "Engenheiro(a) de segurança do trabalho",
  "Engenheiro(a) de software",
  "Engenheiro(a) de telecomunicações",
  "Engenheiro(a) elétrico(a)",
  "Engenheiro(a) mecânico(a)",
  "Engenheiro(a) químico(a)",
  "Engraxate",
  "Enólogo(a)",
  "Escritor(a)",
  "Escultor(a)",
  "Estatístico(a)",
  "Esteticista",
  "Estilista",
  "Estivador(a)",
  "Executor(a) de serviços gerais",
  "Farmacêutico(a)",
  "Faxineiro(a)",
  "Ferramenteiro(a)",
  "Fisioterapeuta",
  "Florista",
  "Fonoaudiólogo(a)",
  "Fotógrafo(a)",
  "Fundidor(a)",
  "Garagista",
  "Garçom/Garçonete",
  "Gari",
  "Geógrafo(a)",
  "Geólogo(a)",
  "Gerente de banco",
  "Gerente de projetos",
  "Gestor(a) ambiental",
  "Gestor(a) de TI",
  "Guarda-costas",
  "Guia turístico(a)",
  "Historiador(a)",
  "Ilustrador(a)",
  "Iluminador(a)",
  "Informático(a)",
  "Instalador(a) de ar condicionado",
  "Instrutor(a) de academia",
  "Instrutor(a) de autoescola",
  "Intérprete",
  "Investigador(a)",
  "Jardineiro(a)",
  "Joalheiro(a)",
  "Jornalista",
  "Ladrilhador(a)",
  "Lavador(a) de carros",
  "Lavador(a) de roupas",
  "Lavrador(a)",
  "Leiteiro(a)",
  "Leiturista",
  "Líder de equipe",
  "Locutor(a)",
  "Maestro(a)",
  "Maquiador(a)",
  "Marceneiro(a)",
  "Massagista",
  "Matemático(a)",
  "Mecânico(a)",
  "Médico(a)",
  "Metalúrgico(a)",
  "Meteorologista",
  "Modelo",
  "Montador(a) de móveis",
  "Motoboy/Motogirl",
  "Motorista",
  "Motorista de ônibus",
  "Museólogo(a)",
  "Músico(a)",
  "Nutricionista",
  "Oceanógrafo(a)",
  "Office boy/Office girl",
  "Oficial de justiça",
  "Operador(a) de caixa",
  "Operador(a) de câmera",
  "Operador(a) de máquinas",
  "Ortopedista",
  "Ourives",
  "Palhaço(a)",
  "Paleontólogo(a)",
  "Palestrante",
  "Pastor(a)",
  "Pediatra",
  "Pedagogo(a)",
  "Pedreiro(a)",
  "Perito(a) criminal",
  "Pescador(a)",
  "Pescador(a) artesanal",
  "Pesquisador(a)",
  "Pintor(a)",
  "Pizzaiolo(a)",
  "Poeta/Poetisa",
  "Policial",
  "Policial rodoviário(a)",
  "Produtor(a) cultural",
  "Produtor(a) rural",
  "Professor(a) particular",
  "Professor(a) universitário(a)",
  "Programador(a)",
  "Promotor(a) de eventos",
  "Psicólogo(a)",
  "Psicopedagogo(a)",
  "Publicitário(a)",
  "Químico(a)",
  "Quiroprático(a)",
  "Radialista",
  "Radiologista",
  "Recreador(a)",
  "Redator(a)",
  "Relações públicas",
  "Reparador(a) de computadores",
  "Repórter",
  "Revisor(a) de textos",
  "Salva-vidas",
  "Sapateiro(a)",
  "Secretário(a)",
  "Segurança",
  "Serralheiro(a)",
  "Servente de pedreiro",
  "Sociólogo(a)",
  "Socorrista",
  "Soldador(a)",
  "Sommelier",
  "Speleologisto(a) - Artes Visuais",
  "Speleologisto(a) - Pintura",
  "Speleologisto(a) - Desenho",
  "Speleologisto(a) - Gravura",
  "Speleologisto(a) - Arte Histórica",
  "Speleologisto(a) - Material ou equipamento de espeleologia",
  "Speleologisto(a) - Outro(s)",
  "Superintendente",
  "Tatuador(a)",
  "Taxista",
  "Técnico(a) agrícola",
  "Técnico(a) de laboratório",
  "Técnico(a) de manutenção",
  "Técnico(a) de segurança do trabalho",
  "Técnico(a) em eletrônica",
  "Técnico(a) em enfermagem",
  "Técnico(a) em radiologia",
  "Teleatendente",
  "Telefonista",
  "Terapeuta ocupacional",
  "Topógrafo(a)",
  "Tradutor(a)",
  "Treinador(a)",
  "Turismólogo(a)",
  "Urbanista",
  "Vaqueiro(a)",
  "Vendedor(a)",
  "Veterinário(a)",
  "Veterinário(a) de pequenos animais"
];

const deficiencias = [
  "Transtorno do espectro autista",
  "Surdocegueira",
  "Surdez",
  "Perturbação emocional",
  "Deficiência auditiva",
  "Deficiência intelectual",
  "Múltiplas deficiências",
  "Deficiência ortopédica",
  "Outra deficiência de saúde",
  "Deficiência específica de aprendizagem",
  "Deficiência de fala ou linguagem",
  "Lesão cerebral traumática",
  "Deficiência visual",
  "Deficiências físicas",
  "Deficiências cognitivas",
  "Deficiências do desenvolvimento",
  "Dificuldades de aprendizagem",
  "Deficiências sensoriais"
];

const familias = [
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8 ou mais",
];

const escolaridade = [
  "Ensino fundamental incompleto",
  "Ensino fundamental completo",
  "Ensino médio incompleto",
  "Ensino médio completo",
  "Ensino superior incompleto",
  "Ensino superior completo",
  "Pós-Graduação"
];

const racas = [
  "Branco(a)",
  "Preto(a)",
  "Amarelo(a)",
  "Pardo(a)",
  "Indígena",
  "Outra",
];

const countries = [
  "Afeganistão", "África do Sul", "Albânia", "Alemanha", "Andorra", "Angola", "Antígua e Barbuda", "Arábia Saudita", "Argélia", "Argentina", "Armênia", "Austrália", "Áustria", "Azerbaijão",
  "Bahamas", "Bahrein", "Bangladesh", "Barbados", "Belarus", "Bélgica", "Belize", "Benin", "Butão", "Bolívia", "Bósnia e Herzegovina", "Botsuana", "Brasil", "Brunei", "Bulgária", "Burquina Faso", "Burundi",
  "Cabo Verde", "Camarões", "Camboja", "Canadá", "Catar", "Cazaquistão", "Chade", "Chile", "China", "Chipre", "Colômbia", "Comores", "Congo-Brazzaville", "Congo-Kinshasa", "Coreia do Norte", "Coreia do Sul", "Costa do Marfim", "Costa Rica", "Croácia", "Cuba",
  "Dinamarca", "Djibouti", "Dominica", "República Dominicana",
  "Egito", "El Salvador", "Emirados Árabes Unidos", "Equador", "Eritreia", "Eslováquia", "Eslovênia", "Espanha", "Estados Unidos", "Estônia", "Eswatini", "Etiópia",
  "Fiji", "Filipinas", "Finlândia", "França",
  "Gabão", "Gâmbia", "Gana", "Geórgia", "Granada", "Grécia", "Guatemala", "Guiana", "Guiné", "Guiné-Bissau", "Guiné Equatorial",
  "Haiti", "Honduras", "Hungria",
  "Iêmen", "Ilhas Marshall", "Índia", "Indonésia", "Irã", "Iraque", "Irlanda", "Islândia", "Israel", "Itália",
  "Jamaica", "Japão", "Jordânia",
  "Kiribati", "Kosovo", "Kuwait", "Laos", "Lesoto", "Letônia", "Líbano", "Libéria", "Líbia", "Liechtenstein", "Lituânia", "Luxemburgo",
  "Macedônia do Norte", "Madagascar", "Malásia", "Malaui", "Maldivas", "Mali", "Malta", "Marrocos", "Maurícia", "Mauritânia", "México", "Mianmar", "Micronésia", "Moçambique", "Moldávia", "Mônaco", "Mongólia", "Montenegro",
  "Namíbia", "Nauru", "Nepal", "Nicarágua", "Níger", "Nigéria", "Noruega", "Nova Zelândia",
  "Omã",
  "Países Baixos", "Palau", "Panamá", "Papua-Nova Guiné", "Paquistão", "Paraguai", "Peru", "Polônia", "Portugal",
  "Quênia", "Quirguistão",
  "Reino Unido", "República Centro-Africana", "República Tcheca", "Romênia", "Ruanda", "Rússia",
  "São Cristóvão e Névis", "San Marino", "Santa Lúcia", "São Tomé e Príncipe", "São Vicente e Granadinas", "Senegal", "Serra Leoa", "Sérvia", "Singapura", "Síria", "Somália", "Sri Lanka", "Suazilândia", "Sudão", "Sudão do Sul", "Suécia", "Suíça", "Suriname",
  "Tailândia", "Tajiquistão", "Tanzânia", "Timor-Leste", "Togo", "Tonga", "Trinidad e Tobago", "Tunísia", "Turcomenistão", "Turquia", "Tuvalu",
  "Ucrânia", "Uganda", "Uruguai", "Uzbequistão",
  "Vanuatu", "Vaticano", "Venezuela", "Vietnã",
  "Zâmbia", "Zimbábue"
];

export { countries, deficiencias, escolaridade, familias, profissoes, racas }